[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-driver",
  "fonts-liberation",
  "libatk-bridge2.0-0",
  "libgtk-3-0",
  "libgbm1",
  "libnss3",
  "libxss1",
  "libasound2"
]

[start]
cmd = "node server.js"
